### ISSUE TITLE
Purpose?

### ISSUE THREAD

**Issue by Zillion01** [IchHabRecht/hide_used_content#5]
Purpose of this extension?

When making IRRE relations to custom content elements. Adding to the TCA of the IRRE element : 

`'overrideChildTca' => [
                'columns' => [
                    'colPos' => [
                        'config' => [
                            'default' => 99
                        ]
                    ]
                ]
            ]`

And add a row 99 in backend layout. Before TYPO3 10, putting the rowcount 1 lower would hide 99 in the backend.
See https://stackoverflow.com/questions/61476644/typo3-v10-rowcount-in-backend-layout-seems-not-to-work-anymore

Now simply tsconfig:
mod.SHARED.colPos_list = 0,1,2,3 etc. To allow which colPos should be visible.

**Comment by IchHabRecht** [comment]
Hi @Zillion01 

of course you can do it manually for each of your elements or the ones any third party extension provides. Or you just use the extension and get an automation. Feel free to not use the extension if you don't need it :-)
