### ISSUE TITLE
Typo3 11 & PHP 8.0 Support

### ISSUE THREAD

**Issue by bh-teufels** [IchHabRecht/hide_used_content#6]
are there already plans for Typo3 11.5 & PHP 8.0 support ?

**Comment by tritum** [comment]
There is a fork for TYPO3 v11: https://github.com/in2code-de/hide_used_content

**Comment by felixranesberger** [comment]
Shoutout goes to @cnmarco for providing the pull request 👍🏻

**Comment by IchHabRecht** [comment]
I finally had some time to release a new version compatible with TYPO3 11.5 and PHP 8.x
